### ISSUE TITLE
RFC: Migrating to a true wiki system like Wiki.js

### ISSUE THREAD

**Issue by hongxuchen** [llvm-wiki/llvm-wiki#23]
## Summary
Migrating from mkdocs to a wiki system like [wiki.js](https://js.wiki/) may be a good idea for collaborative contribution, making llvm.wiki a true wiki site.

## Motivation
For now llvm.wiki is built on mkdocs and github actions. Everything is fine except that it is not easy for a wiki-like collaborative editing:
1. applying a PR flow may discourage most people from contributing.
2. even editing markdown files on GitHub using `Add file`/`Edit this file` button with its online editor is not a good idea, since the result is not what you see on llvm.wiki, and it may lag a few minutes to trigger GitHub actions.
3. It is difficult for multiple contributors edit simultaneously.

In essence, mkdocs is more a documentation than a wiki/collaborative note-taking system.

## Proposed Solution
Use wiki.js instead. I has all the features that mkdocs has provided:
1. markdown editing, with builtin support like GFM and maths;
2. i18n and L10n;
4. nice UIs and themes.
5. ...

The flow will be changed like below (like a normal wiki site):
1. Authorized contributors edit pages directly on llvm.wiki;
6. Authorized contributors audit the edited pages;
7. Edited pages are synced to storage systems like GitHub (an example sync result is [here](https://github.com/The-Wallfacer-Plan/notes/blob/main/openwrt.md)), etc.

## Pros
1. Essential: wiki.js system is designed for collaborative editing; once setup, it is quite user-friendly for the users; and online editing experience is quite pleasant.
2. bonus: 
    1. seems to support `page not found` indicator inside wiki system;
    2. allows for [multiple storage backup and synchronization](https://docs.requarks.io/storage) (Git sync can be bi-directional);
    3. allows for multiple text formats such as asciidocs, rich formats, etc in addition to markdown;
    8. Analytics, commenting, (advanced) searching, are possible.

## Cons
1. It introduces complexity. It is NOT a static site generator, therefore you have to host a site for it rather than purely rely on GitHub pages (hosting setup is easy though).
2. Performance may not be as good as static htmls.

**Comment by inclyc** [comment]
Good motivation overall! llvm-wiki previously cherry-picks all infrastructure from  [OI-wiki](oi-wiki.org). For now it actually does not qualifiy our requirements (as you mentioend).

> a wiki system

AFAIK there are many other wiki systems, is wiki.js the best choice for us?

https://en.m.wikipedia.org/wiki/Comparison_of_wiki_software

> It introduces complexity. It is NOT a static site generator, therefore you have to host a site for it rather than purely rely on GitHub pages (hosting setup is easy though).

So, we need a dedicated team for maintainance?

**Comment by hongxuchen** [comment]
> AFAIK there are many other wiki systems, is wiki.js the best choice for us?

Not sure whether it is the best choice, but I suppose good markdown support should come first. Other alternatives had come into my mind like mediawiki, duowiki, MoinMoinWiki.

> So, we need a dedicated team for maintainance?

Not exactly. The maintenance effort is no bigger than current flow. The setup does require some machine resources and a public IP.

**Comment by inclyc** [comment]
@Lancern @junaire Any ideas?

**Comment by junaire** [comment]
This sounds interesting, however:
1. how much work needs to be done when migrating our current work to Wiki.js? Now we only have a few pages so that should be fine but I still wonder how much work it is.
2. I am strongly against hosting the wiki on our own, because:
    * It's very hard to maintain a website. eg: who is responsible for handling the server downtime?
    * I believe there's very low traffic on the wiki, so it may not be worth spending money on the server.

One possible solution I can come up with is to use some free services like Cloudflare workers, firebase, or something like that. It's free for low-bandwidth websites and maintained by large companies. However, I'm not sure their platforms support the desired app, maybe that's something we can check first.

**Comment by Lancern** [comment]
I agree with @junaire. The idea is great but the biggest problem now is how to host the new wiki system without much cost. I use DigitalOcean the most but unfortunately DigitalOcean doesn't offer a free way to host such a complex application like wiki.js.
