### ISSUE TITLE
Writing an LLVM Pass

### ISSUE THREAD

**Issue by inclyc** [llvm-wiki/llvm-wiki#7]
https://llvm.org/docs/WritingAnLLVMNewPMPass.html
https://llvm.org/docs/WritingAnLLVMPass.html

**Comment by inclyc** [comment]
LLVM is currently migrating the legacy PM to the new one, we can discuss whether to "merge" the official docs (legacy & new) into one here.

**Comment by Lancern** [comment]
Maybe we first just focus on the new PM. After finishing the new PM we shall see if we can merge the legacy stuff into it.

**Comment by inclyc** [comment]
Fixed by #18
